app/models.py
from django.contrib.auth.models import AbstractUser, BaseUserManager
from django.db import models
from django.utils.translation import ugettext_lazy as _


class UserManager(BaseUserManager):
    """Define a model manager for User model with no username field."""

    use_in_migrations = True

    def _create_user(self, email, password, **extra_fields):
        """Create and save a User with the given email and password."""
        if not email:
            raise ValueError('The given email must be set')
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        """Create and save a regular User with the given email and password."""
        extra_fields.setdefault('is_staff', False)
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password, **extra_fields):
        """Create and save a SuperUser with the given email and password."""
        extra_fields.setdefault('is_staff', True)
        extra_fields.setdefault('is_superuser', True)

        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')
        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractUser):
    """User model."""

    username = None
    email = models.EmailField(_('email address'), unique=True)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

    objects = UserManager()

#   """Models for Twitter"""

class Tweet(models.Model):
    content = models.CharField(max_length=200, verbose_name='Tweetnij!: ')
    creation_date = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        ordering = ['-creation_date']

class Message(models.Model):
    sender = models.ForeignKey(User, related_name="sender", on_delete=models.CASCADE)
    receiver = models.ForeignKey(User, related_name="receiver", on_delete=models.CASCADE)
    message_content = models.CharField(max_length=100)
    creation_date = models.DateTimeField(auto_now=True)

app/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.forms import Textarea
from .models import *

class UserLoginForm(forms.Form):
    email = forms.EmailField(max_length=64, label='Login (email)')
    password = forms.CharField(max_length=64, label="Password", widget=forms.PasswordInput)

class SignUpForm(forms.Form):
    email = forms.EmailField(max_length=64, label='Email as Login', help_text='Required. Enter a valid email adress.')
    password1 = forms.CharField(max_length=64, label='Password',
                                widget=forms.PasswordInput(attrs={'placeholder': 'Hasło'}))
    password2 = forms.CharField(
        max_length=64, label='Repeat password',
        widget=forms.PasswordInput(attrs={'placeholder': 'Powtórz hasło'}))

    class Meta:
        user = User
        fields = ('email', 'password1', 'password2')

# tweet create form:
class TweetAddForm(forms.Form):
    class Meta:
        model = Tweet
        fields = '__all__'
        widgets = {
            'name': forms.Textarea(attrs={'cols': 60, 'rows': 40}),
        }

app/views.py
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, HttpResponse
from django.views import View
from django.views.generic import CreateView

from .models import Tweet
from .forms import *



class Base(View):
    def get(self, request):
        tweets = Tweet.objects.all()
        return render(request, 'main.html', {'tweets':tweets})

#User login view:
class UserLogin(View):
    def get(self, request):
        form = UserLoginForm()
        return render(request, 'login.html', {"form": form})
    def post(self, request):
        form = UserLoginForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            password = form.cleaned_data['password']
            user = authenticate(email=email, password=password)
            if user is not None:
                login(request, user)
                #return redirect('/')
            else:
                return HttpResponse('Login or email invalid')
            # error info
            return redirect('/')

 #user log out:
class UserLogout(LoginRequiredMixin, View):
    def get(self, request):
        logout(request)
        return redirect('/')

# user register:
class UserAdd(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, 'register.html', {'form': form})
    def post(self, request):
        form = SignUpForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data.get('email')
            password1 = form.cleaned_data.get('password1')
            password2 = form.cleaned_data.get('password2')
            User.objects.create_user(password=password1, email=email)
            return redirect('login')
        else:
            return render(request, 'register.html', {'form': form})


#create tweet for loged user:
class CreateTweet(LoginRequiredMixin, CreateView):
    template_name = "tweet_add.html"
    model = Tweet
    fields = ['content']

    def form_valid(self, form):
        user = self.request.user
        content = form.cleaned_data.get('content')
        Tweet.objects.create(content=content, user=user)
        return redirect('/')

#User detail site:
class UserDetails(LoginRequiredMixin, View):
    def get(self, request, user_id):
        user_info = User.objects.get(id=user_id)
        tweets = Tweet.objects.filter(user_id=user_id)
        ctx = {
            'user_info': user_info,
            'tweets': tweets,
        }
        return render(request, 'user_side.html', ctx)

class MessageCreate(LoginRequiredMixin, CreateView):
    template_name = "message_create.html"
    model = Message
    fields = ['message_content', 'reciver']

app/templates/base.html
<!DOCTYPE html>

<head>
    <meta charset="UTF-8">
    <title>Twitter Clone</title>
</head>
    {{ request.user.useremail}}
    {% if user.is_authenticated %}
        <a href="{% url 'logout' %}">{{ user.email }} -> logout</a><br>
        <a href="{% url 'user-details' user_id=user.id %}">Your details</a><br>
        <a href="{% url 'create-tweet' %}"> Create new tweet</a>
    {% else %}
        <a href="{% url 'login' %}"> login </a><br>
        <a href="{% url 'register' %}"> Register </a>
    {% endif %}

<body>
<h1><a href="{% url 'main' %}">Twitter Clone</a></h1>
{% block content %}
    <h1>This is only skill show site by Maciej Krywult </h1>
    <h2> Enjoy!</h2>
{% endblock content %}

</body>

app/templates/login.html
{% extends 'base.html' %}

{% block content %}
    <form action="" method="post">
        {% csrf_token %}
        {{ form }}
        <input type="submit" value="login">
    </form>
{% endblock %}

app/templates/main.html
{% extends "base.html" %}

{% block content %}
    <table border="1">
    <tr>
        <td>Tekst tweeta:</td>
        <td>Data utworzenia wpisu:</td>
        <td>Od kogo:</td>
    </tr>
    {% for tweet in tweets %}
    <tr>
        <td><a> {{ tweet.content }}</a></td>
        <td>{{ tweet.creation_date }}</td>
        <td>{{ tweet.user }}</td>
    </tr>

    {% endfor %}
    </table>
{% endblock content %}

app/templates/register.html
{% extends 'base.html' %}

{% block content %}
    <h2>Create your bird</h2>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Register</button>
    </form>
{% endblock %}

app/templates/tweet_add.html
{% extends 'base.html' %}
{%  block content %}
<form action="" method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Tweet!">

</form>
{% endblock %}

app/templates/user_side.html
{% extends 'base.html' %}
{% block content %}


<p>User: {{ user_info.email }}</p>
<p>Tweets: {{ user_info.tweet_set.count }}</p>
<p>Last ligin: {{ user_info.last_login }}</p>
<p> Regstration date {{ user_info.date_joined }}</p>
    <h1>Your Tweets:</h1>
{% for tweet in tweets %}
    <hr>
                <h7>{{ tweet.creation_date|timesince }} ago</h7>
                <h7>{{ tweet.content }}</h7>
                <p><i>{{ tweet.user }}</i></p>
    <hr>
{% endfor %}

{% endblock %}